The National Health and Nutrition Examination Survey (NHANES) Dataset
==============

Research Question:

Is food insecurity associated with signs of inflammation or other chronic diseases?

Welcome to the CAIPH datathon.

Your dataset is the long term NHANES data set. If you aren't familiar with the data set, the wikipedia has a good summary:

> The National Health and Nutrition Examination Survey (NHANES) is a survey research program conducted by the National Center for Health Statistics (NCHS) to assess the health and nutritional status of adults and children in the United States, and to track changes over time.[1] The survey combines interviews, physical examinations and laboratory tests.[citation needed]
>The NHANES interview includes demographic, socioeconomic, dietary, and health-related questions. The examination component consists of medical, dental, and physiological measurements, as well as laboratory tests administered by medical personnel.[citation needed]
>The National Health Survey Act was passed in 1956. This allowed legislative authorization to provide current statistical data on the amount, distribution, and effects on illness and disability in the United States.[2]
>

Unlike some other data sets in this datathon, where datathoners will load their data via CSV, NHanes big and complicated enough that Christopher J. Endres has created an R library explicitly for the purpose of search, loading, and understanding this data set. The R vignette for this library is included in full below, with minor modification to make it interactive. Any errors or issues in this translatio are the fault of the Datathon team.

In [2]:
ensure_library <- function(pkg) {
  pkg_name <- deparse(substitute(pkg))
  if (!requireNamespace(pkg_name, quietly = TRUE)) {
    install.packages(pkg_name)
  }
  library(pkg_name, character.only = TRUE)
}
library(tidyverse)
ensure_library(nhanesA)
nhanesSearch("food security") %>% head()

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

  Variable.Name Variable.Description
1 ADfdsec       Adult food security category for last 12 months
2 CHfdsec       Child food security category for last 12 months
3 HHfdsec       Household food security category for last 12 months
4 FSDAD         Adult food security category for last 12 months
5 FSDCH         Child food security category for last 12 months
6 FSDHH         Household food security category for last 12 months
  Data.File.Name Data.File.Description Begin.Year EndYear Component
1 FSQ            Food Security         1999       2000    Questionnaire
2 FSQ            Food Security         1999       2000    Questionnaire
3 FSQ            Food Security         1999       2000    Questionnaire
4 FSQ_E          Food Security         2007       2008    Questionnaire
5 FSQ_E          Food Security         2007       2008    Questionnaire
6 FSQ_E          Food Security         2007       2008    Questionnaire
  Use.Constraints
1 None
2 None
3 None
4 None
5 None
6 None

Since the NHANES study involves complicated sample weights, you will want to access those variables as well. You can search for variables containing sampling information.

In [5]:
nhanesSearch("weights") %>% head()

  Variable.Name Variable.Description             Data.File.Name
1 WTSA2YR       Two-year A subsample weights     UHM_E
2 WTSA2YR       Environmental A 2 year weights   UHG_E
3 WTSA2YR       Environmental A two year weights UAS_E
4 WTSB2YR       Environmental C 2 year weights   PP_D
5 WTSC2YR       Environmental C 2 year weights   L24PP_C
6 WTSC2YR       Environmental C 2 year weights   L26UPP_C
  Data.File.Description
1 Metals - Urine
2 Mercury: Inorganic - Urine
3 Arsenics - Total & Speciated - Urine
4 Pesticides - Environmental - Urine
5 Pesticides - Environmental - Urine
6 Pesticides - Current Use - Urine (Formerly Priority Pesticides, Non-persistent Pesticide Metabolites)
  Begin.Year EndYear Component  Use.Constraints
1 2007       2008    Laboratory None
2 2007       2008    Laboratory None
3 2007       2008    Laboratory None
4 2005       2006    Laboratory None
5 2003       2004    Laboratory None
6 2003       2004    Laboratory None

In this brief example we take the mean of the age in years in the table DEMO_I, but appropriately weighted.

In [6]:
ensure_library(survey)

demo <- nhanes('DEMO_I')   # demographics table (example cycle)

design <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~WTINT2YR,
  data = demo,
  nest = TRUE
)

svymean(~RIDAGEYR, design)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘minqa’, ‘numDeriv’, ‘mitools’, ‘RcppArmadillo’


Loading required package: grid

Loading required package: Matrix


Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Loading required package: survival


Attaching package: ‘survey’


The following object is masked from ‘package:graphics’:

    dotchart

           mean   SE
RIDAGEYR 37.987 0.63

In [7]:
design

Stratified 1 - level Cluster Sampling design (with replacement)
With (30) clusters.
svydesign(ids = ~SDMVPSU, strata = ~SDMVSTRA, weights = ~WTINT2YR,
    data = demo, nest = TRUE)